# -*- coding: utf-8 -*-
"""01_python_base.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xENnaaeUu63kpn71Azrh6xiKv8G9d_Zq
"""

# Задача 1.1.

my_favorite_songs = 'Waste a Moment, Staying \' Alive, A Sorta Fairytale, Start Me Up, New Salvation'

my_favorite_songs[:my_favorite_songs.find(",")] + my_favorite_songs[my_favorite_songs.rfind(" N"):] + " " + my_favorite_songs[my_favorite_songs.find("S"): my_favorite_songs.rfind(", A")  ] + " " + my_favorite_songs[my_favorite_songs.rfind("St"):my_favorite_songs.rfind(",")]

# Задача 1.2.
# Пункт A.

my_favorite_songs = [
    ['Waste a Moment', 3.03],
    ['New Salvation', 4.02],
    ['Staying\' Alive', 3.40],
    ['Out of Touch', 3.03],
    ['A Sorta Fairytale', 5.28],
    ['Easy', 4.15],
    ['Beautiful Day', 4.04],
    ['Nowhere to Run', 2.58],
    ['In This World', 4.02],
]

x = my_favorite_songs[1] [1] + my_favorite_songs[4] [1] + my_favorite_songs[7] [1]

print("Три песни звучат", round(x, 1), "минут.")

# Задача 1.2.
# Пункт B

my_favorite_songs_dict = {
    'Waste a Moment': 3.03,
    'New Salvation': 4.02,
    'Staying\' Alive': 3.40,
    'Out of Touch': 3.03,
    'A Sorta Fairytale': 5.28,
    'Easy': 4.15,
    'Beautiful Day': 4.04,
    'Nowhere to Run': 2.58,
    'In This World': 4.02,
}

x = my_favorite_songs_dict ["Waste a Moment"] + my_favorite_songs_dict ['Beautiful Day'] + my_favorite_songs_dict ['In This World']

print("Три песни звучат", round(x, 1), "минут.")